version: "3.1"
services:
  test:
    image: test:latest
    container_name: test
    hostname: test
    restart: unless-stopped
    ports:
      - "60080:80"

networks:
  default:
    external:
      name: mynet
